name: Deploy (Maven)

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Github Package Registry
        run: |
          mkdir -p ~/.m2
          printf "<settings><servers><server><id>github</id><username>${{ secrets.ORG_USERNAME }}</username><password>${{ secrets.ORG_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy